# Generated by Django 5.2.5 on 2025-08-20 17:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nota',
            options={'ordering': ['-actualizado']},
        ),
        migrations.AlterModelOptions(
            name='seccion',
            options={'verbose_name': 'Sección', 'verbose_name_plural': 'Secciones'},
        ),
        migrations.AddField(
            model_name='estudiante',
            name='user',
            field=models.OneToOneField(blank=True, help_text='(Opcional) Usuario vinculado para login', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nota',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seccion',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secciones_dictadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nota',
            name='avance1',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)]),
        ),
        migrations.AlterField(
            model_name='nota',
            name='avance2',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)]),
        ),
        migrations.AlterField(
            model_name='nota',
            name='avance3',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)]),
        ),
        migrations.AlterField(
            model_name='nota',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='core.estudiante'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='nota_final',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)]),
        ),
        migrations.AlterField(
            model_name='nota',
            name='participacion',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)]),
        ),
        migrations.AlterField(
            model_name='nota',
            name='proyecto_final',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)]),
        ),
        migrations.AlterField(
            model_name='nota',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='core.seccion'),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='core.curso'),
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together={('estudiante', 'seccion')},
        ),
        migrations.AlterUniqueTogether(
            name='seccion',
            unique_together={('curso', 'nombre')},
        ),
    ]
