# Generated by Django 5.2.5 on 2025-09-29 02:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_nota_options_alter_seccion_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['codigo']},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ['apellido', 'nombre', 'codigo']},
        ),
        migrations.AlterModelOptions(
            name='nota',
            options={'ordering': ['seccion__curso__codigo', 'seccion__nombre', 'estudiante__apellido', 'estudiante__nombre']},
        ),
        migrations.AlterModelOptions(
            name='seccion',
            options={'ordering': ['curso__codigo', 'nombre']},
        ),
        migrations.AddField(
            model_name='curso',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seccion',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='seccion',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='apellido',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nota',
            name='avance1',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='nota',
            name='avance2',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='nota',
            name='avance3',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='nota',
            name='nota_final',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='nota',
            name='participacion',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='nota',
            name='proyecto_final',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['seccion'], name='core_nota_seccion_fee0f5_idx'),
        ),
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['estudiante'], name='core_nota_estudia_7945d2_idx'),
        ),
    ]
